-- menage.tagriculture definition
CREATE TABLE if not exists `tagriculture` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `agriculture-id` int NOT NULL ,
  `level-1-id` int unsigned NOT NULL,
  `occ` int unsigned NOT NULL DEFAULT '1',
  `ag00` longtext COLLATE utf8mb3_unicode_ci,  
  `ag0l` longtext COLLATE utf8mb3_unicode_ci,
  `ag02a` longtext COLLATE utf8mb3_unicode_ci,
  `ag02b` longtext COLLATE utf8mb3_unicode_ci,
  `ag02_m` longtext COLLATE utf8mb3_unicode_ci,
  `ag02c` longtext COLLATE utf8mb3_unicode_ci,
  `ag02d` longtext COLLATE utf8mb3_unicode_ci,
  `ag02e` longtext COLLATE utf8mb3_unicode_ci,
  `ag02f` longtext COLLATE utf8mb3_unicode_ci,
  `ag02ga` longtext COLLATE utf8mb3_unicode_ci,
  `ag02gb` longtext COLLATE utf8mb3_unicode_ci,
    `ag02i` longtext COLLATE utf8mb3_unicode_ci,
  `ag02j` longtext COLLATE utf8mb3_unicode_ci,
  KEY `idx_agriculture_level1id` (`level-1-id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;






CREATE  TABLE if not exists `tcaracteristique` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
   `caracteristique-id` int unsigned NOT NULL,
  `level-1-id` int unsigned NOT NULL,
  `occ` int unsigned NOT NULL DEFAULT '1',
  `c00` longtext COLLATE utf8mb3_unicode_ci,
  `c01n` longtext COLLATE utf8mb3_unicode_ci,
  `c01p` longtext COLLATE utf8mb3_unicode_ci,
  `c01` longtext COLLATE utf8mb3_unicode_ci,
  `c02` longtext COLLATE utf8mb3_unicode_ci,
  `c03` int,
  `c04` longtext COLLATE utf8mb3_unicode_ci,
  `c05` longtext COLLATE utf8mb3_unicode_ci,
  `c05_jj` longtext COLLATE utf8mb3_unicode_ci,
  `c05_mm` longtext COLLATE utf8mb3_unicode_ci,
  `c05_aaaa` longtext COLLATE utf8mb3_unicode_ci,
  `c06` int,
  `c07p` longtext COLLATE utf8mb3_unicode_ci,
  `c07r` longtext COLLATE utf8mb3_unicode_ci,
  `c07d` longtext COLLATE utf8mb3_unicode_ci,
  `c07c` longtext COLLATE utf8mb3_unicode_ci,
  `c08a` longtext COLLATE utf8mb3_unicode_ci,
  `c08b` longtext COLLATE utf8mb3_unicode_ci,
  `c09` longtext COLLATE utf8mb3_unicode_ci,
  `c10` longtext COLLATE utf8mb3_unicode_ci,
  `c10_a` longtext COLLATE utf8mb3_unicode_ci,
  `c11` longtext COLLATE utf8mb3_unicode_ci,
  `c11a` longtext COLLATE utf8mb3_unicode_ci,
  `c12` longtext COLLATE utf8mb3_unicode_ci,
  `c12pra` longtext COLLATE utf8mb3_unicode_ci,
  `c12rra` longtext COLLATE utf8mb3_unicode_ci,
  `c12dra` longtext COLLATE utf8mb3_unicode_ci,
  `c12cra` longtext COLLATE utf8mb3_unicode_ci,
  `c12mra` longtext COLLATE utf8mb3_unicode_ci,
  `c12mra_a` longtext COLLATE utf8mb3_unicode_ci,
  `c12lpra` longtext COLLATE utf8mb3_unicode_ci,
  `c13p` longtext COLLATE utf8mb3_unicode_ci,
  `c13r` longtext COLLATE utf8mb3_unicode_ci,
  `c13d` longtext COLLATE utf8mb3_unicode_ci,
  `c13c` longtext COLLATE utf8mb3_unicode_ci,
  `c13m` longtext COLLATE utf8mb3_unicode_ci,
  `c13m_a` longtext COLLATE utf8mb3_unicode_ci,
  `c13lp` longtext COLLATE utf8mb3_unicode_ci,
  `c14p` longtext COLLATE utf8mb3_unicode_ci,
  `c14r` longtext COLLATE utf8mb3_unicode_ci,
  `c14d` longtext COLLATE utf8mb3_unicode_ci,
  `c14c` longtext COLLATE utf8mb3_unicode_ci,
  `c14m` longtext COLLATE utf8mb3_unicode_ci,
  `c14m_a` longtext COLLATE utf8mb3_unicode_ci,
  `c14lp` longtext COLLATE utf8mb3_unicode_ci,
  `c14me` longtext COLLATE utf8mb3_unicode_ci,
  `c14ae` longtext COLLATE utf8mb3_unicode_ci,
  `c16` longtext COLLATE utf8mb3_unicode_ci,
  `c17` longtext COLLATE utf8mb3_unicode_ci,
  `c18a` longtext COLLATE utf8mb3_unicode_ci,
  `c18b` longtext COLLATE utf8mb3_unicode_ci,
  `c18c` longtext COLLATE utf8mb3_unicode_ci,
  `c18d` longtext COLLATE utf8mb3_unicode_ci,
  `c18e` longtext COLLATE utf8mb3_unicode_ci,
  `c18f` longtext COLLATE utf8mb3_unicode_ci,
  `c18g` longtext COLLATE utf8mb3_unicode_ci,
  `c18h` longtext COLLATE utf8mb3_unicode_ci,
  `c19a` longtext COLLATE utf8mb3_unicode_ci,
  `c19b` longtext COLLATE utf8mb3_unicode_ci,
  `c19c` longtext COLLATE utf8mb3_unicode_ci,
  `c19d` longtext COLLATE utf8mb3_unicode_ci,
  `c19e` longtext COLLATE utf8mb3_unicode_ci,
  `c19ec` longtext COLLATE utf8mb3_unicode_ci,
  `c19f` longtext COLLATE utf8mb3_unicode_ci,
  `c20` longtext COLLATE utf8mb3_unicode_ci,
  `c20a` longtext COLLATE utf8mb3_unicode_ci,
  `c21` longtext COLLATE utf8mb3_unicode_ci,
  `c21a` longtext COLLATE utf8mb3_unicode_ci,
  `c21b` longtext COLLATE utf8mb3_unicode_ci,
  `c22` longtext COLLATE utf8mb3_unicode_ci,
  `c23` longtext COLLATE utf8mb3_unicode_ci,
  `c24` longtext COLLATE utf8mb3_unicode_ci,
  `c24a` longtext COLLATE utf8mb3_unicode_ci,
  `c25` longtext COLLATE utf8mb3_unicode_ci,
  `c25a` longtext COLLATE utf8mb3_unicode_ci,
  `c26` longtext COLLATE utf8mb3_unicode_ci,
  `c26a` longtext COLLATE utf8mb3_unicode_ci,
  `c26b` longtext COLLATE utf8mb3_unicode_ci,
  `c27t` longtext COLLATE utf8mb3_unicode_ci,
  `c27m` longtext COLLATE utf8mb3_unicode_ci,
  `c27f` longtext COLLATE utf8mb3_unicode_ci,
  `c28t` longtext COLLATE utf8mb3_unicode_ci,
  `c28m` longtext COLLATE utf8mb3_unicode_ci,
  `c28f` longtext COLLATE utf8mb3_unicode_ci,
  `c29` longtext COLLATE utf8mb3_unicode_ci,
  `c29a` longtext COLLATE utf8mb3_unicode_ci,
  `c29a_jj` longtext COLLATE utf8mb3_unicode_ci,
  `c29a_mm` longtext COLLATE utf8mb3_unicode_ci,
  `c29a_aaaa` longtext COLLATE utf8mb3_unicode_ci,
  `c29b` longtext COLLATE utf8mb3_unicode_ci,
  `c29c` longtext COLLATE utf8mb3_unicode_ci,
  `c30t` longtext COLLATE utf8mb3_unicode_ci,
  `c30m` longtext COLLATE utf8mb3_unicode_ci,
  `c30f` longtext COLLATE utf8mb3_unicode_ci,
  `c31t` longtext COLLATE utf8mb3_unicode_ci,
  `c31m` longtext COLLATE utf8mb3_unicode_ci,
  `c31f` longtext COLLATE utf8mb3_unicode_ci,
  `c32` longtext COLLATE utf8mb3_unicode_ci,
  `c33` longtext COLLATE utf8mb3_unicode_ci,
  `ind_status` longtext COLLATE utf8mb3_unicode_ci,
  `membre_controle` longtext COLLATE utf8mb3_unicode_ci,
  `is_deleted` longtext COLLATE utf8mb3_unicode_ci,
  `temp_nais` longtext COLLATE utf8mb3_unicode_ci,
  `temp_migration` longtext COLLATE utf8mb3_unicode_ci,
  `temp_migration_1` longtext COLLATE utf8mb3_unicode_ci,
  `temp_survi` longtext COLLATE utf8mb3_unicode_ci,
  `temp_handicap` longtext COLLATE utf8mb3_unicode_ci,
  `temp_activite` longtext COLLATE utf8mb3_unicode_ci,
  `temp_education` longtext COLLATE utf8mb3_unicode_ci,
  `temp_etat_matrimonial` longtext COLLATE utf8mb3_unicode_ci,
  `temp_fecondite` longtext COLLATE utf8mb3_unicode_ci,
  `temp_tic` longtext COLLATE utf8mb3_unicode_ci,
  `tranche_age` varchar(7) DEFAULT NULL,
  `age_19_45` int NOT NULL DEFAULT '0',
  KEY `idx_caracteristique_stats` (`level-1-id`,`c03`,`c06`),
  KEY `idx_caracteristique_femmes_age` (`c03`,`c06`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;




-- menage.tdeces definition
 CREATE TABLE if not exists `tdeces` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
 `deces-id` int unsigned NOT NULL ,
  `level-1-id` int unsigned NOT NULL,
  `occ` int unsigned NOT NULL DEFAULT '1',
  `d02` longtext COLLATE utf8mb3_unicode_ci,
  `d02a` longtext COLLATE utf8mb3_unicode_ci,
  `d03` longtext COLLATE utf8mb3_unicode_ci,
  `d04` longtext COLLATE utf8mb3_unicode_ci,
  `d05` longtext COLLATE utf8mb3_unicode_ci,
  `d06` longtext COLLATE utf8mb3_unicode_ci,
  `d06_a` longtext COLLATE utf8mb3_unicode_ci
 ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;




-- menage.televage definition
 CREATE TABLE if not exists `televage` (
  `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `elevage-id` int unsigned NOT NULL,
  `level-1-id` int unsigned NOT NULL,
  `occ` int unsigned NOT NULL DEFAULT '1',
  `ag03e` longtext COLLATE utf8mb3_unicode_ci,
  `ag03l` longtext COLLATE utf8mb3_unicode_ci,
  `ag03a` longtext COLLATE utf8mb3_unicode_ci,
  `ag03b` longtext COLLATE utf8mb3_unicode_ci
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;



 CREATE TABLE if not exists `temigration` (
`code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `emigration-id` int unsigned NOT NULL,
  `level-1-id` int unsigned NOT NULL,
  `occ` int unsigned NOT NULL DEFAULT '1',
  `em02` longtext COLLATE utf8mb3_unicode_ci,
  `em03n` longtext COLLATE utf8mb3_unicode_ci,
  `em03p` longtext COLLATE utf8mb3_unicode_ci,
  `em04` longtext COLLATE utf8mb3_unicode_ci,
  `em05` longtext COLLATE utf8mb3_unicode_ci,
  `em06m` longtext COLLATE utf8mb3_unicode_ci,
  `em06a` longtext COLLATE utf8mb3_unicode_ci,
  `em07` longtext COLLATE utf8mb3_unicode_ci,
  `em08` longtext COLLATE utf8mb3_unicode_ci,
  `em09` longtext COLLATE utf8mb3_unicode_ci,
  `em09a` longtext COLLATE utf8mb3_unicode_ci,
  `em10` longtext COLLATE utf8mb3_unicode_ci,
  `em11` longtext COLLATE utf8mb3_unicode_ci,
  `em12` longtext COLLATE utf8mb3_unicode_ci,
   KEY `idx_emigration_level1id` (`level-1-id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;




-- menage.thabitat definition
CREATE TABLE if not exists `thabitat` (
 `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `habitat-id` int unsigned NOT NULL,
  `level-1-id` int unsigned NOT NULL,
  `h01` longtext COLLATE utf8mb3_unicode_ci,
  `h01a` longtext COLLATE utf8mb3_unicode_ci,
  `h02` longtext COLLATE utf8mb3_unicode_ci,
  `h03` longtext COLLATE utf8mb3_unicode_ci,
  `h03a` longtext COLLATE utf8mb3_unicode_ci,
  `h04` longtext COLLATE utf8mb3_unicode_ci,
  `h04a` longtext COLLATE utf8mb3_unicode_ci,
  `h05` longtext COLLATE utf8mb3_unicode_ci,
  `h05a` longtext COLLATE utf8mb3_unicode_ci,
  `h06a` longtext COLLATE utf8mb3_unicode_ci,
  `h06b` longtext COLLATE utf8mb3_unicode_ci,
  `h07` longtext COLLATE utf8mb3_unicode_ci,
  `h07a` longtext COLLATE utf8mb3_unicode_ci,
  `h07m` longtext COLLATE utf8mb3_unicode_ci,
  `h08` longtext COLLATE utf8mb3_unicode_ci,
  `h08a` longtext COLLATE utf8mb3_unicode_ci,
  `h09` longtext COLLATE utf8mb3_unicode_ci,
  `h09a` longtext COLLATE utf8mb3_unicode_ci,
  `h10` longtext COLLATE utf8mb3_unicode_ci,
  `h10a` longtext COLLATE utf8mb3_unicode_ci,
  `h11` longtext COLLATE utf8mb3_unicode_ci,
  `h11a` longtext COLLATE utf8mb3_unicode_ci,
  `h12` longtext COLLATE utf8mb3_unicode_ci,
  `h12a` longtext COLLATE utf8mb3_unicode_ci,
  `h13` longtext COLLATE utf8mb3_unicode_ci,
  `h13a` longtext COLLATE utf8mb3_unicode_ci,
  `h14(1)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(2)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(3)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(4)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(5)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(6)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(7)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(8)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(9)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(10)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(11)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(12)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(13)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(14)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(15)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(16)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(17)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(18)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(19)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(20)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(21)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(22)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(23)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(24)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(25)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(26)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(27)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(28)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(29)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(30)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(31)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(32)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(33)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(34)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(35)` longtext COLLATE utf8mb3_unicode_ci,
  `h14(36)` longtext COLLATE utf8mb3_unicode_ci,
  `h1426` longtext COLLATE utf8mb3_unicode_ci
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;




-- menage.tmenage definition
CREATE TABLE if not exists `tmenage` (
 `code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `menage-id` int unsigned NOT NULL,
  `level-1-id` int unsigned NOT NULL,
  `id01` longtext COLLATE utf8mb3_unicode_ci,
  `id02` longtext COLLATE utf8mb3_unicode_ci,
  `id03` longtext COLLATE utf8mb3_unicode_ci,
  `id05` longtext COLLATE utf8mb3_unicode_ci,
  `id06` longtext COLLATE utf8mb3_unicode_ci,
  `id07` longtext COLLATE utf8mb3_unicode_ci,
  `id10` longtext COLLATE utf8mb3_unicode_ci,
  `xm01` longtext COLLATE utf8mb3_unicode_ci,
  `xm04` longtext COLLATE utf8mb3_unicode_ci,
  `xm06` longtext COLLATE utf8mb3_unicode_ci,
  `xm08` longtext COLLATE utf8mb3_unicode_ci,
  `xm08lo` longtext COLLATE utf8mb3_unicode_ci,
  `xm08la` longtext COLLATE utf8mb3_unicode_ci,
  `xm09` longtext COLLATE utf8mb3_unicode_ci,
  `xm10` longtext COLLATE utf8mb3_unicode_ci,
  `xm11` longtext COLLATE utf8mb3_unicode_ci,
  `xm11_jj` longtext COLLATE utf8mb3_unicode_ci,
  `xm11_mm` longtext COLLATE utf8mb3_unicode_ci,
  `xm11_aaaa` longtext COLLATE utf8mb3_unicode_ci,
  `xm12` longtext COLLATE utf8mb3_unicode_ci,
  `xm12h` longtext COLLATE utf8mb3_unicode_ci,
  `xm12m` longtext COLLATE utf8mb3_unicode_ci,
  `xm13` longtext COLLATE utf8mb3_unicode_ci,
  `xm13_jj` longtext COLLATE utf8mb3_unicode_ci,
  `xm13_mm` longtext COLLATE utf8mb3_unicode_ci,
  `xm13_aaaa` longtext COLLATE utf8mb3_unicode_ci,
  `xm14` longtext COLLATE utf8mb3_unicode_ci,
  `xm14h` longtext COLLATE utf8mb3_unicode_ci,
  `xm14m` longtext COLLATE utf8mb3_unicode_ci,
  `xm50` longtext COLLATE utf8mb3_unicode_ci,
  `xm20` longtext COLLATE utf8mb3_unicode_ci,
  `xm30` longtext COLLATE utf8mb3_unicode_ci,
  `xm40` int,
  `xm60` longtext COLLATE utf8mb3_unicode_ci,
  `xm41` longtext COLLATE utf8mb3_unicode_ci,
  `d00` longtext COLLATE utf8mb3_unicode_ci,
  `d01` longtext COLLATE utf8mb3_unicode_ci,
  `ag01` longtext COLLATE utf8mb3_unicode_ci,
  `ag01b` longtext COLLATE utf8mb3_unicode_ci,
  `em00` longtext COLLATE utf8mb3_unicode_ci,
  `em01` longtext COLLATE utf8mb3_unicode_ci,
  `intro_membre` longtext COLLATE utf8mb3_unicode_ci,
  `meta_rep` longtext COLLATE utf8mb3_unicode_ci,
  `meta_start` longtext COLLATE utf8mb3_unicode_ci,
  `meta_end` longtext COLLATE utf8mb3_unicode_ci,
  `meta_last_modify_date` longtext COLLATE utf8mb3_unicode_ci,
  `meta_duration` longtext COLLATE utf8mb3_unicode_ci,
  `meta_calc_duration` longtext COLLATE utf8mb3_unicode_ci,
  `meta_intro` longtext COLLATE utf8mb3_unicode_ci,
  `tel_repondant` longtext COLLATE utf8mb3_unicode_ci,
  `men_exist_denombrement` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(1)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(2)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(3)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(4)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(5)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(6)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(7)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(8)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(9)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(10)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(11)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(12)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(13)` longtext COLLATE utf8mb3_unicode_ci,
  `ag02h(14)` longtext COLLATE utf8mb3_unicode_ci
   KEY `idx_menage_geo_filters` (`code_region`,`code_departement`,`code_commune`,`mo_zd`)
  -- KEY `idx_menage_stats` (`level-1-id`,`xm40`,`nb_residents`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;


CREATE TABLE if not exists `tstats` (
`code_region` varchar(1) DEFAULT NULL,
  `region` varchar(50) NOT NULL,
  `code_departement` varchar(3) DEFAULT NULL,
  `departement` varchar(150) NOT NULL,
  `code_commune` varchar(5) DEFAULT NULL,
  `commune` varchar(150) NOT NULL,
  `mo_zs` varchar(15) NOT NULL,
  `mo_zd` varchar(15) NOT NULL,
  `mo_id` int DEFAULT NULL,
  `stats-id` int unsigned NOT NULL,
  `level-1-id` int unsigned NOT NULL,
  `nb_residents_rp_ra` int,
  `nb_residents_rp_ra_homme` int,
  `nb_residents_rp_ra_femme` int,
  `nb_resident_present_total_rp` int,
  `nb_resident_present_homme_rp` int,
  `nb_resident_present_femme_rp` int,
  `nb_resident_absent_total_ra` int,
  `nb_resident_absent_homme_ra` int,
  `nb_resident_absent_femme_ra` int,
  `nb_visiteur_total` int,
  `nb_visiteur_homme` int,
  `nb_visiteur_femme` int,
  `nb_total_membre_menage_rp_ra_vi` int,
  `nb_total_membre_menage_homme_rp_ra_vi` int,
  `nb_total_membre_menage_femme_rp_ra_vi` int,
  `nb_total_membre_menage_present_visiteur_rp_vi` int,
  `nb_total_membre_menage_present_visiteur_homme_rp` int,
  `nb_total_membre_menage_present_visiteur_femme_rp` int
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;